

  <!-- jQuery -->
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  
  
  <!-- // Foundation JS-->
  <script src="foundation-4.3.1/js/foundation.min.js"></script>
  
 
 
  <!-- // This one is not needed - it's the un-minified version of foundation.min.js
  <script src="foundation-4.3.1/js/foundation/foundation.js"></script>
  -->
 
  <!-- // other foundation scripts, uncomment to activate 
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.alerts.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.clearing.js"></script>

  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.cookie.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.dropdown.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.forms.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.joyride.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.magellan.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.orbit.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.reveal.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.section.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.tooltips.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.topbar.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.interchange.js"></script>
  
  <script src="<?=WEBSITE;?>/foundation-4.3.1/js/foundation/foundation.placeholder.js"></script>
  
  -->
  
		<script src="js/cashhimi-custom.js"></script>
		<script>
			var desktopDropdown = new Cashhimi.Dropdown("desktop-nav");
		</script>
  
		<script src="js/classie.js"></script>
		<script src="js/mlpushmenu.js"></script>
		<script>
			var pushMenu = new mlPushMenu( document.getElementById( 'mp-menu' ), document.getElementById( 'trigger' ) );
		</script>
		
    <script>
      $( document ).ready(function() {
         $('header').addClass('animated fadeInDown');
         $('.container').addClass('animated fadeInUp');
         $('.container').addClass('animated fadeInUp');
         $('.row.footer').css('opacity', '1');
      });
    </script>
    

