  <!-- // Modernizr.js, built into foundation -->
<!--   // N.B. We are using a special build that merges the tests for Foundation and the PushMenu -->
  <script src="js/custom.modernizr.js"></script>
  
  
  <link rel="stylesheet" href="foundation-4.3.1/css/foundation.css" />
  <link rel="stylesheet" href="css/push-menu.css" />
  


   <? /*
  <!-- // webicons css -->
  <link rel="stylesheet" type="text/css" href="<?=WEBSITE;?>/css/general_foundicons.css" media="all"> 
  <link rel="stylesheet" type="text/css" href="<?=WEBSITE;?>/css/social_foundicons.css" media="all"> 
*/ ?>


  <!-- // Our custom css that overrides foundation's base CSS -->
  <link rel="stylesheet" type="text/css" href="css/cashhimi-custom.css" media="all"> 