<div class='row collapse hide-for-small footer'>
	<div class='large-8 columns'>
		<ul class='footer'>
			<li><a href='#'>CONTACT <span class='footer-crush'>US</span></a></li>
			<li><a href='#'>PRIVACY <span class='footer-crush'>POLICY</span></a></li>
			<li><a href='#'>TERMS &amp; CONDITIONS	</a></li>
			<li><a href='#'>SHIPPING &amp; RETURNS	</a></li>
			<li><strong>EMPOWERED BY ZINDIGO</strong></li>
		</ul>
		
	</div>
	<div class='large-4 columns text-right'>
		<form data-abide>
			<input type='text' name='subscribe' id='subscribe' required placeholder="SUBSCRIBE TO US">
			<a class='btn submit'>Submit</button>
			<a class='btn facebook'>Follow Us On Facebook</a>
			<a class='btn twitter'>Follow Us On Twitter</a>
			<a class='btn email'>Email us</a>
		</form>
	</div>
</div>