<div class='row'>
<div class='small-5 columns'>
<p>Cenan Abas Sel took the road less traveled on her quest to become a luxury accessories designer. Upon graduating university in her native country, Turkey, Cenan set out to put her business administration degree aside for greater good of fashion. 
</p>
<p>With a team of 30 women, Cenan began producing exquisite knitted designs hand-sewn with precious Swarovski crystals that only elevated the aesthetic of an already unmatched design.</p>

<p>In 2007, Cenan introduced the States to beautifully crafted leather outerwear and accessories. Garnering praise from industry insiders, Cenan returned to Turkey and opened her very own showroom and workshop, thus giving birth to Cashhimi.
</p>


<p>Close to Abas Sels heart, the name Cashhimi is derived from the initials of her name, the surname of her husband, and the first two letters of her sons names.</p>
</div>
</div>