<div class='row'>
<div class='small-12 columns'>
<p class='hide-for-medium-up text-center swipe-for-more'>SWIPE FOR MORE</p>
<div class="slideshow-wrapper hide-for-medium-up">
<div class='preloader'></div>

<ul data-orbit class="press-slider">
  <li>
			<a href='#'>
				<img src='images/mag-1.jpg'>
				<div class="orbit-caption">Lorem Ipsum Bacon Cheeseburger</div>
			</a>	
  </li>
  <li>
			<a href='#'>
				<img src='images/mag-2.jpg'>
				<div class="orbit-caption">Lorem Ipsum Zoidberg</div>
			</a>	
  </li>
  <li>
			<a href='#'>
				<img src='images/mag-1.jpg'>
				<div class="orbit-caption">Lorem Ipsum Bourbon Spackle</div>
			</a>	
  </li>
  <li>
			<a href='#'>
				<img src='images/mag-2.jpg'>
				<div class="orbit-caption">Lorem Ipsum Nec Sunt Inter What</div>
			</a>	
  </li>
</ul>
</div> <!-- end slideshow-wrapper -->

<div class="mag-slider show-for-medium-up" id="press-slider2">
	<ul>
	  <li>
				<a href='images/mag-1.jpg' class="fancybox" rel="press-gallery" title="Lorem Ipsum Bacon Cheeseburger">
					<img src='images/mag-1.jpg'>
				</a>	
	  </li>
	  <li>
				<a href='images/mag-2.jpg' class="fancybox" rel="press-gallery" title="Lorem Ipsum Zoidberg">
					<img src='images/mag-2.jpg'>
				</a>	
	  </li>
	  <li>
				<a href='images/mag-1.jpg' class="fancybox" rel="press-gallery" title="Lorem Ipsum Bourbon Spackle">
					<img src='images/mag-1.jpg'>
				</a>	
	  </li>
	  <li>
				<a href='images/mag-2.jpg' class="fancybox" rel="press-gallery" title="Lorem Ipsum Nec Sunt Inter What">
					<img src='images/mag-2.jpg'>
				</a>	
	  </li>
	</ul>
	<a class="lookbook-prev" href="#"></a>
	<a class="lookbook-next" href="#"></a>
</div>
	

</div> <!-- end small-12 columns -->
</div>