<div class='row fluid'>
<div class='small-12 columns'>
<p class='hide-for-medium-up text-center swipe-for-more'>SWIPE FOR MORE</p>
<div class="slideshow-wrapper">
<div class='preloader'></div>

<ul data-orbit class="products-slider">
  <li>
  		
	<ul class='small-block-grid-2 large-block-grid-3'>
		<? for($i=0;$i<9;$i++){ ?>
		<li class='text-center'>
			<a href='#'>
				<img src='images/handbag.jpg'>
			<p class='product'>
			Le Doux RD (Python)
			<br>
			$1,250
			</p>
			</a>
		</li>
		
		<? } ?>
	</ul>
	
  </li>
  <li>
  
  
	<ul class='small-block-grid-2 large-block-grid-3'>
		<? for($i=0;$i<9;$i++){ ?>
		<li class='text-center'>
			<a href='#'>
				<img src='images/handbag2.jpg'>
			<p class='product'>
			Le Doux RD (Python)
			<br>
			$1,250
			</p>
			</a>
		</li>
		
		<? } ?>
	</ul>
	
	
  </li>
  <li>
  
  
	<ul class='small-block-grid-2 large-block-grid-3'>
		<? for($i=0;$i<9;$i++){ ?>
		<li class='text-center'>
			<a href='#'>
				<img src='images/handbag.jpg'>
			<p class='product'>
			Le Doux RD (Python)
			<br>
			$1,250
			</p>
			</a>
		</li>
		
		<? } ?>
	</ul>
	
	
  </li>
</ul>
</div> <!-- end slideshow-wrapper -->
	

</div> <!-- end small-12 columns -->
</div>